/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "message_constants.h"

namespace wire {

const messageConstants g_message_constants;

messageConstants::messageConstants() {
}

} // namespace

