/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef metadata_CONSTANTS_H
#define metadata_CONSTANTS_H

#include "metadata_types.h"

namespace wire { namespace metadata {

class metadataConstants {
 public:
  metadataConstants();

};

extern const metadataConstants g_metadata_constants;

}} // namespace

#endif
