/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "metadata_constants.h"

namespace wire { namespace metadata {

const metadataConstants g_metadata_constants;

metadataConstants::metadataConstants() {
}

}} // namespace

