// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WanderService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::wire;

class WanderServiceHandler : virtual public WanderServiceIf {
 public:
  WanderServiceHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void getNextMessage(HeaderAndMessage& _return) {
    // Your implementation goes here
    printf("getNextMessage\n");
  }

  void getPreviousMessage(HeaderAndMessage& _return) {
    // Your implementation goes here
    printf("getPreviousMessage\n");
  }

  void getWmOpScreenshotURL(std::string& _return, const int64_t user, const int64_t timestamp, const std::string& hash) {
    // Your implementation goes here
    printf("getWmOpScreenshotURL\n");
  }

  void getFiles(Files& _return) {
    // Your implementation goes here
    printf("getFiles\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WanderServiceHandler> handler(new WanderServiceHandler());
  shared_ptr<TProcessor> processor(new WanderServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

